### ISSUE TITLE
Streaming to local file.

### ISSUE THREAD

**Issue by fvlasie** [manishkatyan/bbb-streaming#8]
Hello, Would it possible to use this plugin to stream to a local mp4 file? 
This could provide on-the-fly recordings of classes that would include everything, even external shared media.
Thank you!

**Comment by arun-hel** [comment]
@fvlasie With a little tweak to  [stream.js](https://github.com/manishkatyan/bbb-streaming/blob/master/build/stream.js), you can directly write the stream to local file
